apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: workflow  
  namespace: default
spec:
  type: workflow.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379  
  - name: redisPassword
    value: ""              